global: &global
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: 5
  host: localhost

development:
  database: vim_genius_development
  <<: *global

test: &test
  database: vim_genius_test
  <<: *global

production:
  database: vim_genius_production
  <<: *global

cucumber:
  <<: *test
